Numpy array and basics

In [4]:
import numpy as np

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array",arr_2d)

1D array:  [1 2 3 4 5]
2d array [[1 2 3]
 [4 5 6]]


##list vs numpy array

In [ ]:
py_list = [1,2,3]
print("python list multiplication ",py_list*2)

np_array = np.array([1,2,3]) #element wise multiplication
print("python array multiplication ",np_array*2)

import time 
start = time.time()
py_list = [i*2 for  i in range(100000)]
print("\n list operation time: ",time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n numpy operation time: ",time.time()-start)

python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]

 list operation time:  0.007569789886474609

 numpy operation time:  0.0018010139465332031


#creating array from scratch

In [12]:
zeroes = np.zeros((3,4))
print("zeroes array: \n", zeroes)

ones = np.ones((2,3))
print("one array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,11,2)
print("sequence array: \n", sequence)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.68080408 0.72738219 0.57332301]
 [0.66282118 0.17410175 0.64404408]]
sequence array: 
 [ 0  2  4  6  8 10]


#Vecotor,matrix and tensor

In [14]:
vector = np.array([1,2,3])
print("vecotor ",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ",tensor)

vecotor  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Array properties

In [17]:
arr = np.array([[1,2,3],
                [4,5,6],])
print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("Dtype ",arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


#Array reshaping

In [18]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3,4))
print("\n reshaped array ",reshaped)

flattened = reshaped.flatten()
print("\n flattened array ",flattened)

#ravel (return view , instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ",raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed array ",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
